### ISSUE TITLE
Error! Potentially cant find process module

### ISSUE THREAD

**Issue by SirajHabsaia** [spicy/StrafeAnalyzer#1]
I get this error whenever i try to inject
(game running in main menu with -insecure
![6Car1Pw](https://user-images.githubusercontent.com/69755038/181913760-ad2c03b5-2676-430d-8a5f-6193abc2f37a.png)
)
Can you maybe give us the .dll so we can inject manually ?

**Comment by spicy** [comment]
My injector was created prior to Windows 11, and does not work on particular versions of it. I may refactor the injector in the future. The dll can be built from the source code and instructions in the readme
