### ISSUE TITLE
A special unproccessed situation happened in your app.

### ISSUE THREAD

**Issue by Miswift** [spicy/StrafeAnalyzer#3]
![image](https://user-images.githubusercontent.com/98270895/212537498-d58b164c-98ed-40c7-95e5-324ff94a6497.png)

**Comment by spicy** [comment]
This issue is caused by a dependency. Since your windows default language is non-english, some values get parsed incorrectly when trying to get the most recent version from github. You can inject the DLL manually instead of using the provided loader. I am not intending on updating the loader.
